# Generated by Django 6.0.3 on 2026-03-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('Tech_stack1', models.ImageField(blank=True, null=True, upload_to='')),
                ('Tech_stack2', models.ImageField(blank=True, null=True, upload_to='')),
                ('Tech_stack3', models.ImageField(blank=True, null=True, upload_to='')),
                ('Link', models.CharField(max_length=255)),
            ],
        ),
    ]
