# Generated by Django 6.0.3 on 2026-03-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Github',
            field=models.CharField(blank=True, null=True),
        ),
    ]
