# Generated by Django 6.0.3 on 2026-04-24 14:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_project_github'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', cloudinary.models.CloudinaryField(max_length=255, verbose_name='file')),
            ],
        ),
    ]
