# Generated by Django 6.0.3 on 2026-04-24 22:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='cv'),
        ),
    ]
