# Generated by Django 6.0.3 on 2026-04-24 22:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0004_alter_profile_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
