# Generated by Django 6.0.3 on 2026-04-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='')),
                ('Description', models.CharField()),
                ('Created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
